services:
  mongo:
    image: mongo
    ports:
    - 27017:27107
    environment:
      MONGO_INIT_ROOT_USERNAME: admin
      MONGO_INIT_ROOT_PASSWORD: qwerty

  mongo-express:
    image: mongo-express
    ports:
    - 8081:8081
    environment:
      MG_CONFIG_MONGODB_ADMINUSERNAME: admin
      MG_CONFIG_MONGODB_ADMINPASSWORD: qwerty
      MG_CONFIG_MONGODB_URL: mongodb://admin:qwerty@mongo:27017/
